name: food_craft
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.7

flutter_native_splash:
  color: "003566"
  image: "assets/images/logo_foodCraft.png"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_foodCraft.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/